-- MK Earn Hub: Supabase database schema
-- Run this in Supabase SQL Editor.
-- IMPORTANT: keep service_role keys server-side only.

create table if not exists public.profiles (
  id bigint primary key,
  username text,
  first_name text,
  last_name text,
  balance bigint not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_events (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('daily','ad','task')),
  amount bigint not null check (amount > 0),
  event_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.profiles(id) on delete cascade,
  amount bigint not null check (amount > 0),
  method text not null,
  destination text not null,
  status text not null default 'pending' check (status in ('pending','approved','paid','rejected')),
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists reward_events_user_idx on public.reward_events(telegram_id, created_at desc);
create index if not exists withdrawals_user_idx on public.withdrawal_requests(telegram_id, created_at desc);

-- Atomic reward function: prevents duplicate event_key rewards.
create or replace function public.add_reward(
  p_telegram_id bigint,
  p_type text,
  p_amount bigint,
  p_event_key text
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_balance bigint;
begin
  insert into public.profiles(id) values (p_telegram_id)
    on conflict (id) do nothing;

  insert into public.reward_events(telegram_id,type,amount,event_key)
  values (p_telegram_id,p_type,p_amount,p_event_key)
  on conflict (event_key) do nothing;

  if found then
    update public.profiles
    set balance = balance + p_amount, updated_at = now()
    where id = p_telegram_id
    returning balance into new_balance;
  else
    select balance into new_balance from public.profiles where id=p_telegram_id;
  end if;

  return new_balance;
end;
$$;

-- Withdrawal request function. Production deployments should call this only
-- from a trusted backend after validating Telegram initData.
create or replace function public.request_withdrawal(
  p_telegram_id bigint,
  p_amount bigint,
  p_method text,
  p_destination text
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  request_id bigint;
begin
  if p_amount <= 0 then raise exception 'Invalid amount'; end if;
  if length(trim(p_destination)) < 3 then raise exception 'Invalid destination'; end if;

  update public.profiles
  set balance = balance - p_amount, updated_at = now()
  where id = p_telegram_id and balance >= p_amount;

  if not found then raise exception 'Insufficient balance'; end if;

  insert into public.withdrawal_requests(telegram_id,amount,method,destination)
  values(p_telegram_id,p_amount,p_method,p_destination)
  returning id into request_id;

  return request_id;
end;
$$;

-- Do not expose tables/functions broadly through an unauthenticated client.
revoke all on public.profiles from anon, authenticated;
revoke all on public.reward_events from anon, authenticated;
revoke all on public.withdrawal_requests from anon, authenticated;
revoke all on function public.add_reward(bigint,text,bigint,text) from public, anon, authenticated;
revoke all on function public.request_withdrawal(bigint,bigint,text,text) from public, anon, authenticated;
